theme: jekyll-theme-cayman
title: Bem Vindo a Elëve Vidav 
description: O Caminho segue por aqui
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3
plugins:
  - jemoji
  - jekyll-mentions
