theme: jekyll-theme-cayman
markdown: kramdown
<p align = "center">
 <img src ="https://github.com/Vinimoura/vidav/blob/master/eleve%20vida%20logo.jpg">
</p>
title: Bem Vindo a Elëve Vidav 
description: O Caminho segue por aqui 
